refactor(Popup): create first internal component popup used by tooltip and popover
scaleway/ultraviolet pull request #2714
Opened 2023-07-11 09:25 UTC by matthprost

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

Creation of a new folder `src/internalComponents`. This folder will contains all components that are being used within the package and will never be exported outside of it. The goal is to have a centralised place for reusable components.

In this PR we created `Popup` a component that show on screen as popup depending on the location of the children. This component is used by `Tooltip` but also by `Popover` and will later be used for `SelectInput`, `Menu` and any other components needing `Popup` behavior.

2023-07-13 12:57 UTC, chambo-e requested changes

2023-07-13 12:57 UTC, chambo-e commented on packages/ui/src/components/Tooltip/index.tsx
>  type TooltipProps = {
Can we reuse Popup type here ?

2023-07-17 13:53 UTC, philibea commented on packages/ui/src/internalComponents/Popup/index.tsx
> +const StyledTooltip = styled.div<StyledTooltipProps>`
shouldForwardProp ?

2023-07-17 13:58 UTC, philibea commented on packages/ui/src/internalComponents/Popup/__tests__/__tests__/index.test.tsx
> +    shouldMatchEmotionSnapshot(<Popup text="test">Hover me</Popup>))
shouldMatchEmotionSnapshotWithPortal

2023-07-17 13:58 UTC, philibea commented on packages/ui/src/internalComponents/Popup/__tests__/__tests__/index.test.tsx
> +    shouldMatchEmotionSnapshot(<Popup>Hover me</Popup>))
shouldMatchEmotionSnapshotWithPortal

2023-07-17 13:59 UTC, philibea commented on packages/ui/src/components/Tooltip/__tests__/__snapshots__/index.test.tsx.snap
>  <div
check here if should use shouldMatchEmotionSnapshotWithPortal instead :)

2023-07-19 08:45 UTC, chambo-e approved these changes

2023-07-19 09:22 UTC, JulienSaguez approved these changes

2023-07-19 12:50 UTC, philibea approved these changes

2023-07-20 08:04 UTC, merged