docs: add font import explanation
scaleway/ultraviolet pull request #2715
Opened 2023-07-11 09:33 UTC by matthprost

## Summary

## Type

- Documentation

### Summarise concisely:

#### What is expected?

The readme missing an important information about the font and which one to import.

2023-07-12 09:05 UTC, chambo-e requested changes

2023-07-12 09:05 UTC, chambo-e commented on packages/ui/README.md
> +<link href="https://fonts.cdnfonts.com/css/jetbrains-mono" rel="stylesheet">
```suggestion
<link href="https://fonts.cdnfonts.com/css/asap?styles=20325,20323,20320" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/jetbrains-mono-2?styles=156604" rel="stylesheet">
```

No need to load the whole planet :)

2023-07-12 09:34 UTC, chambo-e approved these changes

2023-07-17 07:48 UTC, philibea approved these changes

2023-07-17 08:01 UTC, merged