fix: event workflow not consistent
scaleway/ultraviolet pull request #2988
Opened 2023-10-04 14:07 UTC by DorianMaliszewski

## Summary

## Type

- Bug

### Summarise concisely:

#### What is expected?

Handle close/show event properly do not have waterfall effects

#### The following changes where made:

(Describe what you did)

1.

2.

3.

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| url  | screenshot | screenshot |
| url  | screenshot | screenshot |

2023-10-04 14:55 UTC, matthprost requested changes

2023-10-04 14:55 UTC, matthprost commented on packages/ui/src/components/MenuV2/__stories__/WithModal.stories.tsx
> +      <TextInput name="test" />
Can you add a label also, so we can know what is it about in the story

2023-10-06 09:53 UTC, matthprost approved these changes

2023-10-09 13:13 UTC, ModuloM approved these changes

2023-10-10 07:30 UTC, merged