feat(modal): replace function names by good ones
scaleway/ultraviolet pull request #3008
Opened 2023-10-10 07:29 UTC by DorianMaliszewski

## Summary

## Type

- Enhancement

### Summarise concisely:

#### What is expected?

Replace function names by good ones (close/show)

#### The following changes where made:

1. Change function names

2.

3.

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| url  | screenshot | screenshot |
| url  | screenshot | screenshot |

2023-10-10 08:17 UTC, matthprost requested changes

2023-10-12 08:34 UTC, matthprost approved these changes

2023-10-12 08:34 UTC, matthprost commented
Some unit testing is broken but then it's green for me 🚀

2023-10-12 15:35 UTC, BABAK0T0 approved these changes

2023-10-13 09:44 UTC, merged