feat(dateinput): update design and add range date
scaleway/ultraviolet pull request #3011
Opened 2023-10-11 12:16 UTC by JulienSaguez

## Summary
update design and add range date
## Type
- Feature

For the reference, check the figma https://www.figma.com/file/XHoO4V9LOFEFkAZsocYJ83/Ultraviolet%3A-Core-Components?type=design&node-id=7493%3A121027&mode=design&t=KHeUecaJBVlUWfK4-1 ant the ticket https://jira.infra.online.net/browse/DS-579

2023-10-12 08:32 UTC, matthprost requested changes

2023-10-12 08:32 UTC, matthprost commented on packages/ui/src/components/DateInput/index.tsx
> +    : format(value)
Here you need to check if `valueStart` and `valueEnd` exists or if they don't we have an input containing only `-`

<img width="989" alt="Screenshot 2023-10-12 at 10 19 29" src="https://github.com/scaleway/ultraviolet/assets/15812968/46f1668f-0f88-4739-bade-b84c6fd0f723">

2023-10-12 08:32 UTC, matthprost commented on packages/ui/src/components/DateInput/__stories__/Range.stories.tsx
> +export const Range = Template.bind({})
Could you make this story like controlled so we can test the component on storybook? I know designers will want to test it haha

2023-10-12 08:32 UTC, matthprost commented on .changeset/fair-boxes-carry.md
> +update design and add range date
You can precise the prop that has been added and to what component, for example:

```suggestion
Component `<DateInput />` updates:
- Design update
- New prop available `selectRange` allowing the user to select a range of dates
```

2023-10-12 08:32 UTC, matthprost commented on packages/ui/src/components/DateInput/__stories__/Range.stories.tsx
> +}
This is the old way to describe a story please use this instead:

```suggestion
Range.parameters = {
  docs: {
    description: {
          story: 'With `startDate` and `endDate` you can define a range of dates',
      }
  },
}
```

2023-10-12 08:32 UTC, matthprost commented on packages/ui/src/components/DateInput/__stories__/Exclude.stories.tsx
> +}
Same goes for here:

```suggestion
Exclude.parameters = {
  docs: {
    description: {
        story: 'With `excludeDates` you can define a array of dates to exclude',
      }
  },
}
```

2023-10-12 08:32 UTC, matthprost commented on packages/ui/src/components/DateInput/__tests__/index.test.tsx
> +    ))
You need to add another test for `excludeDates` prop too or the testing coverage will go down

2023-10-12 15:08 UTC, PetmePant requested changes
1) There is an issue when you swap months with the button navigations. It rearranges like small portion of the location and it changes the width of the picker. The month text shouldn't change the container width or change the button's location.

2) When range is enabled the selected dates looks a bit weird with some numeric numbers that we should hide.

3) need to change prop name from selectRange to range 

Notes:
*I couldn't check the range functionality 
*Overall styles look like design, perfect


![Screenshot 2023-10-12 at 6 04 04 PM](https://github.com/scaleway/ultraviolet/assets/8331633/4148f450-ced3-4f87-b6c9-2497d6ea63d8)

https://github.com/scaleway/ultraviolet/assets/8331633/28324ff3-7c31-4c61-a32e-e46860ab41a4

2023-10-17 13:21 UTC, PetmePant approved these changes

2023-10-19 08:34 UTC, Lawndlwd approved these changes

2023-10-19 08:48 UTC, merged