feat(experimental-popup): move popup as an experimental component
scaleway/ultraviolet pull request #3018
Opened 2023-10-12 15:42 UTC by BABAK0T0

## Summary

## Type

- Enhancement

### Summarise concisely:

Move Popup component as an experimental component

#### What is expected?

Make the Popup component available

#### The following changes where made:

1. I moved the component from an internal usage to an experimental one

2023-10-12 15:44 UTC, matthprost requested changes

2023-10-12 15:44 UTC, matthprost commented on packages/ui/src/components/Popup/index.tsx
> + * @experimental
```suggestion
 * @experimental This component is experimental and may be subject to breaking changes in the future.
```

2023-10-13 09:23 UTC, johnrazeur approved these changes

2023-10-13 09:25 UTC, ModuloM approved these changes

2023-10-13 09:28 UTC, merged