feat(stepper): update component stepper with prop size and labelposition
scaleway/ultraviolet pull request #3085
Opened 2023-10-26 14:07 UTC by JulienSaguez

## Summary

## Type

- Feature

#### What is expected?

update component stepper with prop size and labelposition

For the reference, check the figma https://www.figma.com/file/XHoO4V9LOFEFkAZsocYJ83/%5BCore%5D-Core?type=design&node-id=9924%3A119162&mode=design&t=KFPgzkAXzhRvPvYS-1 and the ticket https://jira.infra.online.net/browse/DS-587

2023-10-26 14:12 UTC, DorianMaliszewski commented on packages/ui/src/components/Stepper/index.tsx
> +    height: 2,
We should not have this hardcoded but comes from theme no ?

2023-10-26 14:13 UTC, DorianMaliszewski commented on packages/ui/src/components/Stepper/index.tsx
> +const SIZES = {
```suggestion
const LINE_HEIGHT_SIZES = {
```

better to understand the usage ?

2023-10-30 15:43 UTC, matthprost commented
@JulienSaguez can you rebase your branch it won't trigger the deploy action until it is done, thanks 🙏

2023-10-31 09:47 UTC, ModuloM approved these changes

2023-10-31 09:47 UTC, ModuloM commented on packages/ui/src/components/Stepper/index.tsx
> +  size?: 'small' | 'medium'
I think you'll need two tests for this.

2023-10-31 09:48 UTC, JulienSaguez commented on packages/ui/src/components/Stepper/index.tsx
> +  size?: 'small' | 'medium'
Yes i can add test for the two props

2023-11-02 11:23 UTC, PetmePant requested changes
1) Need to change the prop options for labelPosition to bottom and right

2) Need to fix a small bug on the bullet number on small with right orientation, the text is not aligned center

![Screenshot 2023-11-02 at 1 01 41 PM](https://github.com/scaleway/ultraviolet/assets/8331633/cc230cdd-6fce-499e-b1b5-23a713b99d51)
![Screenshot 2023-11-02 at 1 01 37 PM](https://github.com/scaleway/ultraviolet/assets/8331633/815a251e-c025-4fdf-999d-835eb8bc6fcd)

2023-11-02 15:12 UTC, merged