feat: new component ContentCardGroup
scaleway/ultraviolet pull request #3096
Opened 2023-10-30 15:31 UTC by fabienhebert

## Summary

## Type

- Feature

### Summarise concisely:

add a new component `ContentCardGroup` to package ultraviolet/plus

## Relevant logs and/or screenshots

![Capture d’écran 2023-10-30 à 16 29 53](https://github.com/scaleway/ultraviolet/assets/8116991/65dca8dd-6d2d-4915-bd62-5b72d9808a2b)

2023-10-31 12:57 UTC, PetmePant approved these changes

2023-10-31 14:07 UTC, ModuloM approved these changes

2023-10-31 14:48 UTC, matthprost requested changes
I think you forgot to export it into `packages/plus/src/components/index.ts`

2023-11-06 15:07 UTC, matthprost requested changes

2023-11-06 15:09 UTC, BABAK0T0 approved these changes

2023-11-06 15:33 UTC, merged