feat(Tabs): add subtitle props
scaleway/ultraviolet pull request #3143
Opened 2023-11-13 17:31 UTC by philibea

## Summary

## Type

- Enhancement
### Summarise concisely:

📄 Specification 
Max width: TBD and it seems we need truncation script on the description when its long (it should be limited to 1 line)
Alignment : left-align
Text color : neutral weak when not selected
Text color : primary when tab is active 
Typography: bodySmall

FRONT SPECIFICATIONS
We need to add a prop subtitle into Tabs.Tab component that will be shown according to the figma proto.

We need to align all Tabs.Tab on top

We don't need to add the description in the Tab Menu.

#### What is expected?

Add a Subtitle to the Tab only on the Nav component ( not Menu ) 

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| url  |  <img width="1025" alt="Capture d’écran 2023-11-14 à 17 53 33" src="https://github.com/scaleway/ultraviolet/assets/14060273/6cab6d68-0d71-4281-97b5-0cd7cd1abae3"> |  <img width="942" alt="Capture d’écran 2023-11-14 à 17 50 47" src="https://github.com/scaleway/ultraviolet/assets/14060273/a0adac5a-edd1-41f3-b232-e9909471aa24"> |
| url  | <img width="645" alt="Capture d’écran 2023-11-14 à 17 55 17" src="https://github.com/scaleway/ultraviolet/assets/14060273/fd3c5ef9-68eb-4207-8e7a-bd48a6319662"> |  <img width="653" alt="Capture d’écran 2023-11-14 à 17 55 44" src="https://github.com/scaleway/ultraviolet/assets/14060273/43102624-98f2-4ff7-aa95-be7ab79f0c20"> |

Note:

Migrate Menu to MenuV2 is more complex and required a focus on that @matthprost

2023-11-15 11:26 UTC, PetmePant requested changes
1) Spacing between title and subtitle should be 4px
![Screenshot 2023-11-15 at 1 05 17 PM](https://github.com/scaleway/ultraviolet/assets/8331633/3b4901e0-b2bc-44cd-ab81-505bce206d8a)

2) Text color on subtitle should be neutralWeak
![Screenshot 2023-11-15 at 1 05 21 PM](https://github.com/scaleway/ultraviolet/assets/8331633/6c48fc96-deb2-49c6-ab0d-8e40a3ff4358)

3) There is a missalignment on the badge
![Screenshot 2023-11-15 at 1 05 30 PM](https://github.com/scaleway/ultraviolet/assets/8331633/bac6af05-e380-4947-bd50-93690d574de3)

4) This case will never occur so it might be better not to show it. When subtitle will be enabled it will be for all tabs
![Screenshot 2023-11-15 at 1 05 45 PM](https://github.com/scaleway/ultraviolet/assets/8331633/a2b94cf6-b174-4387-87de-7aa8f00e95bb)

2023-11-15 16:46 UTC, philibea commented
> 1. Spacing between title and subtitle should be 4px
>    ![Screenshot 2023-11-15 at 1 05 17 PM](https://user-images.githubusercontent.com/8331633/283101246-3b4901e0-b2bc-44cd-ab81-505bce206d8a.png)
> 2. Text color on subtitle should be neutralWeak
>    ![Screenshot 2023-11-15 at 1 05 21 PM](https://user-images.githubusercontent.com/8331633/283101375-6c48fc96-deb2-49c6-ab0d-8e40a3ff4358.png)
> 3. There is a missalignment on the badge
>    ![Screenshot 2023-11-15 at 1 05 30 PM](https://user-images.githubusercontent.com/8331633/283101406-bac6af05-e380-4947-bd50-93690d574de3.png)
> 4. This case will never occur so it might be better not to show it. When subtitle will be enabled it will be for all tabs
>    ![Screenshot 2023-11-15 at 1 05 45 PM](https://user-images.githubusercontent.com/8331633/283101518-a2b94cf6-b174-4387-87de-7aa8f00e95bb.png)

@PetmePant  Everything should be corrected

2023-11-15 17:10 UTC, matthprost approved these changes

2023-11-15 17:10 UTC, matthprost commented on packages/ui/src/components/Tabs/__stories__/Template.stories.tsx
> +    // </div>
To remove the comment?

2023-11-16 10:43 UTC, PetmePant approved these changes

2023-11-16 13:33 UTC, merged