refactor(DateInput): to use new text input and new design styles
scaleway/ultraviolet pull request #3391
Opened 2024-01-31 17:14 UTC by matthprost

## Summary

## Type

- Enhancement

### Summarise concisely:

#### What is expected?

Refactoring of date input to follow new design specs.

## Relevant logs and/or screenshots

![Screenshot 2024-01-31 at 18 13 56](https://github.com/scaleway/ultraviolet/assets/15812968/7305fb0c-6272-4cf7-8721-6f8c2eca0d59)

2024-01-31 17:22 UTC, fabienhebert approved these changes

2024-02-01 10:08 UTC, PetmePant requested changes
1) Required prop seems that is not functioning 
2) Tooltip prop seems to be broken and in a wrong placement.

2024-02-01 14:37 UTC, johnrazeur commented on packages/ui/src/components/TextInputV2/index.tsx
> +                value={value === null ? '' : value}
We should handle `undefined` value too.

2024-02-01 16:50 UTC, alexandre-combemorel approved these changes

2024-02-02 09:27 UTC, mhervouet commented
Please put the suffix icon disabled in the disabled state.

2024-02-05 14:07 UTC, matthprost commented on packages/ui/src/components/DateInput/__stories__/Template.tsx
> +  required: true,
Oh right my mistake I will fix it to avoid duplication

2024-02-05 14:09 UTC, matthprost commented on packages/form/src/components/DateField/__tests__/index.tsx
> +          await userEvent.click(select)
Yes you are right I wanted to remove `fireEvent` a bit too fast haha

2024-02-05 14:14 UTC, matthprost commented
> Please put the suffix icon disabled in the disabled state.

Done ✅ 

![Screenshot 2024-02-05 at 15 06 30](https://github.com/scaleway/ultraviolet/assets/15812968/2410b0b2-65e9-4231-bcaf-626020c844c5)

2024-02-05 14:25 UTC, mhervouet approved these changes

2024-02-05 15:13 UTC, merged