fix(CheckboxField): remove array value
scaleway/ultraviolet pull request #3409
Opened 2024-02-05 08:26 UTC by johnrazeur

## Summary

## Type

- Bug

### Summarise concisely:

#### The following changes where made:

- Remove array value (use `CheckboxGroupField` for that).
- Add id prop.

2024-02-05 09:18 UTC, matthprost requested changes

2024-02-05 09:18 UTC, matthprost commented on .changeset/ninety-ghosts-carry.md
> +CheckboxField now support only key/value
```suggestion
`CheckboxField` now support only key/value
```

2024-02-05 09:19 UTC, matthprost requested changes

2024-02-05 09:19 UTC, matthprost commented on packages/form/src/components/CheckboxField/index.tsx
> -  value,
You can't remove a prop like that or it will be breaking change. Instead you can mark it as deprecated using JSDoc

2024-02-13 09:35 UTC, vincentaudebert commented
Apart from matthias comment, all good to me. If it gets deprecated, what will it do though?

2024-02-14 10:38 UTC, matthprost approved these changes

2024-02-20 08:31 UTC, vincentaudebert approved these changes

2024-02-20 09:02 UTC, fabienhebert approved these changes

2024-02-20 09:03 UTC, fabienhebert commented
> Apart from matthias comment, all good to me. If it gets deprecated, what will it do though?

You can still use initialValues then `setValue`, if you need to change value in code

2024-02-23 14:03 UTC, merged