fix: add flex-wrap to breadcrumb list
scaleway/ultraviolet pull request #3451
Opened 2024-02-14 15:56 UTC by rachidBensaid

## Summary

Add a flex-wrap to the breadcrumb `ol`

## Type

- Bug

### Summarise concisely:

#### What is expected?

on mobile device, the breadcrumb should be wrapped gracefully

## Relevant logs and/or screenshots

| Page | Before | After |
| :--- | :-----:| -----:|
| [url](https://storybook.ultraviolet.scaleway.com/?path=/docs/components-navigation-breadcrumbs--docs) | ![Capture d’écran 2024-02-14 à 16 52 25](https://github.com/scaleway/ultraviolet/assets/25226974/3881f713-9406-4f0f-9e4f-25ac02a35b6b) | ![Capture d’écran 2024-02-14 à 16 54 00](https://github.com/scaleway/ultraviolet/assets/25226974/40d9b2d1-37fa-4479-b622-567162197eb4) |

2024-02-14 16:09 UTC, matthprost requested changes

2024-02-14 16:09 UTC, matthprost commented on .changeset/purple-ducks-impress.md
> +add flex-wrap to breadcrumb list
```suggestion
Add `flex-wrap` on component `<Breadcrumbs />`
```

2024-02-14 16:27 UTC, matthprost commented
The CI is failing also cause the snapshots are not up to date also, you can run `pnpm run test:unit -u` and push the generated file 😄

2024-02-15 09:00 UTC, matthprost approved these changes

2024-02-16 14:52 UTC, johnrazeur approved these changes

2024-02-16 14:53 UTC, BABAK0T0 approved these changes

2024-02-16 14:55 UTC, matthprost commented
Everything is green @rachidBensaid I'm merging your PR 😄

2024-02-16 14:55 UTC, merged