refactor: migrate faq from shire to ultraviolet plus
scaleway/ultraviolet pull request #3466
Opened 2024-02-16 10:25 UTC by lisalupi

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

`FAQ` component added to ultraviolet/plus
#### The following changes were made:

1. Migrate the component from shire to ultraviolet

2. Add component to storybook

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| url  | screenshot | screenshot |
| url  | screenshot | screenshot |

2024-02-16 14:12 UTC, matthprost requested changes

2024-02-16 14:12 UTC, matthprost commented on .changeset/real-spoons-cough.md
> -Fix prop `type` on component `<TextInputFieldV2 />` that wasn't working properly
This is weird it shouldn't be here, maybe if you rebase and push it will disappear?

2024-02-16 14:13 UTC, matthprost requested changes
You need to export your component in `packages/plus/src/components/index.ts`, I think I forgot to tell you for Conversation component also, so you can do both in that PR

2024-02-19 08:48 UTC, alexandre-combemorel commented on packages/plus/src/components/FAQ/__stories__/index.stories.tsx
> +} as Meta
prefere`satisfies` instead of `as`, like that you get typescript error when you change the type :)

2024-02-19 08:49 UTC, alexandre-combemorel approved these changes

2024-02-19 09:11 UTC, matthprost commented on .changeset/real-spoons-cough.md
> -Fix prop `type` on component `<TextInputFieldV2 />` that wasn't working properly
@lisalupi this is still an issue, did you try rebase on main?

2024-02-19 13:17 UTC, matthprost approved these changes

2024-02-19 13:50 UTC, merged