feat: new DynamicIllustrations component
scaleway/ultraviolet pull request #3491
Opened 2024-02-22 16:10 UTC by lisalupi

## Summary

## Type

- Feature
- Enhancement

### Summarise concisely:

#### What is expected?

New illustrations and new component in ultraviolet/illustrations
#### The following changes were made:

(Describe what you did)

1. New component `DynamicIllustration`: adapt the illustration to the theme

2. 11 new illustrations (+ dark variant) added

2024-02-23 09:16 UTC, matthprost requested changes

2024-02-23 13:28 UTC, PetmePant approved these changes

2024-02-23 13:57 UTC, BABAK0T0 approved these changes

2024-02-26 09:11 UTC, matthprost requested changes

2024-02-26 09:11 UTC, matthprost commented on packages/illustrations/src/components/DynamicIllustration/Illustrations.tsx
> +export type IllustrationsKeys = {
Could you add a little comment here to explain why we do that so we won't forget over time 😄

2024-02-26 09:11 UTC, matthprost commented on packages/illustrations/src/components/DynamicIllustration/__stories__/List.stories.tsx
> +      <Stack direction="row" gap={1} alignItems="center">
When doing a map in react you need to provide a key

2024-02-26 09:11 UTC, matthprost commented on packages/illustrations/src/components/DynamicIllustration/index.tsx
> +  height = 'auto',
Any reason to set it auto by default? What if we leave it undefined by default?

2024-02-27 13:09 UTC, matthprost approved these changes
Let's goo 🚀

2024-02-27 13:42 UTC, merged