refactor(Menu): new style and behavior
scaleway/ultraviolet pull request #3631
Opened 2024-04-05 12:34 UTC by matthprost

## Summary

## Type

- Bug
- Feature
- Enhancement
- Documentation
- Migration
- Refactor

### Summarise concisely:

#### What is expected?

Refactoring of `<MenuV2 />` component with a new style and implement following props:
- New prop `size`: `small`, `medium`, `large`
- New variable `primary` in `sentiment` prop
- New prop `triggerMethod`: `click`, `hover` (default is `click`) it will trigger the menu to open on click or hover

## Relevant logs and/or screenshots

![Screen Recording 2024-04-08 at 17 26 39](https://github.com/scaleway/ultraviolet/assets/15812968/754eb473-4daf-4107-bedf-a83781422df9)

2024-04-09 09:38 UTC, JulienSaguez approved these changes

2024-04-09 12:22 UTC, lisalupi approved these changes

2024-04-15 09:27 UTC, mhervouet commented
<img width="212" alt="Capture d’écran 2024-04-15 à 11 26 24" src="https://github.com/scaleway/ultraviolet/assets/145689179/cfa1afbf-63dd-494d-9e4a-aa66184eb1bd">
<img width="194" alt="Capture d’écran 2024-04-15 à 11 26 39" src="https://github.com/scaleway/ultraviolet/assets/145689179/3deb5b70-0a35-4e49-8c87-e93dc446251a">
Border of the last item of the list must be removed .

2024-04-15 10:17 UTC, PetmePant requested changes
- When hovering an item apart from background, text should also go to :hover color (it remains in the same currently)
- Padding in the menu should be 4px and not 2px (top/bottom/left/right)
- Margin between groups (header or separator) should be 4px and not 2px when they are added.
- Badges/icons/action icon in the menu should be always i[n the right side](https://www.figma.com/file/syW4gpSJAUJUXrgQQn3mdA/%5BPlayground%5D-Core-%26-Plus-Component?type=design&node-id=6544%3A160981&mode=design&t=MaAqMxSnX2nCEUiz-1) and not following text (to avoid staircase effect)

2024-04-15 16:16 UTC, PetmePant approved these changes

2024-04-16 08:32 UTC, merged