fix: change navitem text color
scaleway/ultraviolet pull request #3693
Opened 2024-04-22 13:46 UTC by lisalupi

## Summary

## Type

- Bug

### Summarise concisely:

#### What is expected?

Text in `Navigation.Item` should be textDefault and not textWeak

2024-04-23 08:35 UTC, BABAK0T0 approved these changes

2024-04-23 08:56 UTC, PetmePant commented
Seems good :)

2024-04-23 08:56 UTC, matthprost approved these changes

2024-04-23 08:58 UTC, PetmePant requested changes
Text seems as it should but the icons are still in weak 

![April 23 Screenshot from Matthias Prost (1)](https://github.com/scaleway/ultraviolet/assets/8331633/3bc43b8a-d6ab-4c71-95f9-c35305be1544)

2024-04-24 13:36 UTC, PetmePant approved these changes

2024-04-24 13:42 UTC, merged