feat(Navigation): new pinned feature and reorder
scaleway/ultraviolet pull request #3717
Opened 2024-04-26 16:05 UTC by matthprost

## Summary

## Type

- Enhancement

### Introducing pin feature on Navigation ✨

Navigation is nice for traveling around in your website but it lacked some customization. Pinned feature is here to overcome this issue and provide a new way to customize your navigation. This feature can be enabled adding `pinnedFeature` on your `<NavigationProvider />`

![Screen Recording 2024-04-26 at 17 55 32](https://github.com/scaleway/ultraviolet/assets/15812968/46b54572-d82a-48cb-9f53-fa31f896407e)

Pinned feature allows you to pin / unpin your favorite items until it reach the limit you've set using `pinLimit` on your `<NavigationProvider />`.
It also allows you to re-order your pinned items by using drag n drop and placing it in the order you like.

All your pinned items can be accessed with the hook `useNavigation()`:

```tsx
// pinnedItems = ['myitem1', 'myitem2']
const { pinnedItems } = useNavigation()

// Save in local storage to keep the pinned items on refresh
useEffect(() => {
   localStorage.setItem('pinnedItems', pinnedItems.toString())
}, [pinnedItems])
```

You can of course provide your initially pinned items to the `<NavigationProvider />` by using the prop `initialPinned`.

2024-04-29 09:15 UTC, PetmePant requested changes
1) Issue with menu and active item while pinned. The pin item is not getting hidden when and overlaps with badge. (check video)

https://github.com/scaleway/ultraviolet/assets/8331633/587a3393-160e-44fc-9bfd-248655290d74

2) Alignment issue for the title/label of each pinned item and nav group header.
<img width="326" alt="Screenshot 2024-04-29 at 12 12 50 PM" src="https://github.com/scaleway/ultraviolet/assets/8331633/1f93f9e0-e01c-4df9-aa8a-0a583858bf67">

3) Pinned section should be always visible and with an empty state when no elements are pinned.

4) While reorder we should disable the initial nav item that is dragged

5) Drag & drop handler (cursor) should appear when you hover the drag icon/action and whole you drag and drop the cursor should be different.

6) When you pin an item you should have a toaster message

7) No items from the pinned section can be active similar to the rest of the items.

2024-04-30 08:34 UTC, fabienhebert approved these changes

2024-04-30 09:34 UTC, DorianMaliszewski commented on packages/plus/src/components/Navigation/components/PinnedItems.tsx
> +              <div style={{ position: 'relative' }} key={item}>
? maybe use styled component

2024-04-30 09:35 UTC, DorianMaliszewski commented on packages/plus/src/components/Navigation/components/PinnedItems.tsx
> +            <div style={{ position: 'relative' }}>
Same here use a styled component

2024-05-02 09:24 UTC, matthprost commented on packages/plus/src/components/Navigation/components/Item.tsx
> +}>`
Cannot be used as MenuV2.Item does not spread all it's props

2024-05-02 11:49 UTC, merged