feat: unitinput
scaleway/ultraviolet pull request #3724
Opened 2024-04-29 15:58 UTC by lisalupi

## Summary

## Type

- Feature

### Summarise concisely:

#### What is expected?

New component `<UnitInput />`!
Also, "disabled" is now optional for the options in <SelectInputV2 />
#### The following changes where made:

1. New component with tests + stories

2. Optional prop `disabled` for the options in selectinputV2

2024-04-30 08:12 UTC, matthprost requested changes

2024-04-30 08:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +  minValue?: number
You can name it `max` and `min` in order to follow same naming as `NumberInputV2`

2024-04-30 08:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +}
For the following props: name, id, disabled, placeholder, autoFocus, required, and if you find more. You can do:

```ts
} & InputHTMLAttributes<HTMLInputElement>,
  | 'name'
  | 'id'
  | 'placeholder'
  | ...
```

2024-04-30 08:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +  notice?: string
Notice has been replace by helper you can remove it

2024-04-30 08:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +      <UnitInputWrapper
There is too many borders 

<img width="228" alt="Screenshot 2024-04-30 at 09 58 05" src="https://github.com/scaleway/ultraviolet/assets/15812968/eaf1f974-3f22-4d10-9639-dd221428b8b8">

It should have one unique border + a border separation between both components

2024-04-30 08:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +        onMouseLeave={() => setHovered(false)}
This you don't need I believe you can do that with full css, for instance you could say in a parent container:

```css
&:hover {
  ${UnitInputWrapper} {
     ....
   }
}
```

2024-04-30 08:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +            }
Same goes for focus, this shouldn't be done in JS but in CSS with a parent container you should be able to manage all

2024-04-30 08:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +          id={`${name}-unit`}
The id should be based using `id` provided in the parent if it is provided:

```tsx
id={id ? `${id}-unit` : undefined}
```

And the StyledInput too should have an id then

2024-04-30 08:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +  success?: boolean
Should be a `string | boolean` in order to follow what we did with other inputs

2024-04-30 08:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +      ) : null}
And so here you can also follow what has been done with other inputs and success, error props

2024-04-30 08:13 UTC, matthprost requested changes

2024-04-30 08:13 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +  }, [])
What is this for ? 😅

2024-05-02 08:00 UTC, matthprost requested changes

2024-05-02 08:00 UTC, matthprost commented on packages/ui/src/components/SelectInputV2/index.tsx
> +                  <Text
Label already exists in this context you don't need to recheck it

2024-05-02 08:00 UTC, matthprost commented on packages/ui/src/components/SelectInputV2/index.tsx
> +                {required && label ? (
Same here you can only check if required exists

2024-05-02 08:01 UTC, matthprost requested changes

2024-05-02 08:01 UTC, matthprost commented on packages/ui/src/components/UnitInput/__stories__/Playground.stories.tsx
> +      <div style={{ display: 'inline-flex' }}>
Can you add a `height: '200px'` or more in order to see correctly the select input part in storybook?

<img width="1038" alt="Screenshot 2024-05-02 at 10 01 10" src="https://github.com/scaleway/ultraviolet/assets/15812968/ab1c7d6c-030c-4919-a8e9-6fd2e6bd9100">

2024-05-13 13:46 UTC, matthprost requested changes

2024-05-13 13:46 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +  max = 99999,
Any specific reason to limit max to 99999? Might be better to go with `Number.MAX_SAFE_INTEGER` as we do it in NumberInputV2

2024-05-13 13:46 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +  min = 1,
Same here why 1 and not 0?

2024-05-13 13:49 UTC, matthprost requested changes

2024-05-13 13:49 UTC, matthprost commented on packages/ui/src/components/UnitInput/__stories__/State.stories.tsx
> +)
You need to get the props and spread it in components or storybook won't add code snippet for some reasons:
![Screenshot 2024-05-13 at 15 48 27](https://github.com/scaleway/ultraviolet/assets/15812968/3efb2f8c-5c0d-49a3-9fb1-2a7797a1be6e)

```suggestion
export const States: StoryFn<typeof UnitInput> = (props) => (
  <Stack gap={2}>
    <UnitInput
      options={optionsSelect}
      success="success"
      label="Success"
      name="Success"
      {...props}
    />
    <UnitInput
      options={optionsSelect}
      error="error"
      label="Error"
      name="Error"
      {...props}
    />
  </Stack>
)
```

2024-05-13 13:49 UTC, matthprost commented on packages/ui/src/components/UnitInput/__stories__/Disabled.stories.tsx
> +export const Disabled: StoryFn<typeof UnitInput> = () => (
Same here you need to spread props

2024-05-13 13:50 UTC, matthprost requested changes

2024-05-13 13:50 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +  disabled = false,
There is an issue with disabled, seems like mouse pointer is not disabled when hovering number input part but it is when hovering select input part

2024-05-15 08:01 UTC, matthprost approved these changes
Except those last feedbacks everything is fine for me congrats! 🚀

2024-05-15 08:12 UTC, lisalupi commented on packages/ui/src/components/UnitInput/index.tsx
> +  }, [])
forgot to delete it ^^

2024-05-15 12:59 UTC, mhervouet approved these changes

2024-05-17 08:41 UTC, merged