feat(Slider): new component
scaleway/ultraviolet pull request #3918
Opened 2024-06-25 12:53 UTC by lisalupi

## Summary

## Type

- Feature

### Summarise concisely:

#### What is expected?

New component `<Slider />`

2024-07-01 14:07 UTC, matthprost requested changes

2024-07-01 14:07 UTC, matthprost commented on packages/ui/src/components/Slider/SingleSlider.tsx
> +    return null
```suggestion
    return undefined
```

2024-07-01 14:07 UTC, matthprost commented on packages/ui/src/components/Slider/SingleSlider.tsx
> +      ) : null}
label is same in both single and double, couldn't it be unified in a`Label.tsx` component?

2024-07-01 14:08 UTC, matthprost requested changes
Just noticed also the options label under seems not aligned with the slider

![Screenshot 2024-07-01 at 16 07 00](https://github.com/scaleway/ultraviolet/assets/15812968/ae037e15-ab2a-4730-9b03-8fc885939b30)

2024-07-01 15:45 UTC, lisalupi commented on packages/ui/src/components/Slider/DoubleSlider.tsx
> +  opacity: 1;
no, forgot to delete that ^^

2024-07-01 15:47 UTC, lisalupi commented on packages/ui/src/components/Slider/DoubleSlider.tsx
> +  optionsUnit,
well it shouldn't be different, i can merge both

2024-07-03 07:56 UTC, PetmePant approved these changes

2024-07-03 09:03 UTC, matthprost requested changes

2024-07-04 07:52 UTC, matthprost approved these changes

2024-07-05 12:17 UTC, radhi-nasser-scaleway approved these changes

2024-07-05 12:59 UTC, ValentinRLL approved these changes

2024-07-05 13:07 UTC, merged