feat(Illustrations): ipam illustration
scaleway/ultraviolet pull request #3939
Opened 2024-07-01 13:04 UTC by lisalupi

## Summary

## Type

- Feature

### Summarise concisely:

#### What is expected?

New illustration: `ipam`

2024-07-01 13:40 UTC, matthprost requested changes

2024-07-01 13:40 UTC, matthprost commented on .changeset/calm-wasps-vanish.md
> +"@ultraviolet/illustrations": patch
Could be a minor instead as it's an addition and not a fix 😄

2024-07-02 09:06 UTC, matthprost approved these changes

2024-07-03 09:02 UTC, vincentaudebert approved these changes

2024-07-03 09:04 UTC, merged