feat(ProgressBar): new props
scaleway/ultraviolet pull request #4205
Opened 2024-09-05 15:14 UTC by lisalupi

## Summary

## Type

- Enhancement

### Summarise concisely:

#### What is expected?

`<ProgressBar />`:
- new prop `label`
- new prop `showProgress`: show/hide percentage of progress
- new prop `direction`: defines the position of the label & percentage

2024-09-06 09:16 UTC, PetmePant approved these changes

2024-09-06 09:52 UTC, mhervouet approved these changes

2024-09-07 13:01 UTC, radhi-nasser-scaleway commented on packages/ui/src/components/ProgressBar/__tests__/index.test.tsx
> +  it(`renders correctly with label, label description and showprogress, direction column`, () =>
```suggestion
  it(`renders correctly with label, label description and showProgress, direction column`, () =>
```

same for other occurrences in the files

2024-09-07 13:04 UTC, radhi-nasser-scaleway approved these changes

2024-09-09 07:53 UTC, matthprost requested changes

2024-09-09 07:53 UTC, matthprost commented on packages/ui/src/components/ProgressBar/index.tsx
> +        {labelDescription}
you could wrap label description into a text component if `typeof labelDescription === 'string'`

2024-09-09 07:53 UTC, matthprost commented on packages/ui/src/components/ProgressBar/__stories__/Label.stories.tsx
> +)
this could be in an individual story, we would have label and labelDescription explanation and appart, direction. What do you think?

2024-09-12 15:20 UTC, matthprost approved these changes

2024-09-12 15:22 UTC, merged