fix: style and spacing for form elements
scaleway/ultraviolet pull request #4238
Opened 2024-09-13 15:12 UTC by lisalupi

## Summary

## Type

- Bug

### Summarise concisely:

#### What is expected?

Make sure every form element follow the guidelines

#### The following changes were made:

Guidelines
- **Legend**: BodyStrong - NeutralTextStrong  
- **Description**: BodySmall - NeutralTextStrong  
- **Label**: LARGE = BodyStrong - NeutralTextStrong   SMALL = BodySmallStrong  - NeutralTextStrong  
- **Placeholder**:  LARGE = Body - NeutralTextWeak SMALL = BodySmall - NeutralTextWeak
- **Value**: LARGE = Body - NeutralTextStrong   SMALL = BodySmall -  NeutralTextStrong  
- **Helper**:  Caption - NeutralTextWeak
- **Error**: Caption -  DangerText  
- **Success**:  Caption - SuccesText  
- **Spacing**: must have the same spacing (ex of problem: helpers at 4px for inputs but 8px for checkbox)

& use `Icons` correctly for those component (import icon directly instead of legacy)

2024-09-17 12:12 UTC, matthprost requested changes

2024-09-17 12:12 UTC, matthprost commented on packages/ui/src/components/TextArea/index.tsx
> +                  prominence="strong"
There is small issue with the disabled state, not related to your changes tho
<img width="1046" alt="Screenshot 2024-09-17 at 14 09 37" src="https://github.com/user-attachments/assets/c08b59ea-db14-46e3-b267-3b61696eb825">

2024-09-17 12:12 UTC, matthprost commented on packages/ui/src/components/UnitInput/index.tsx
> +          {error ? <AlertCircleIcon sentiment="danger" /> : null}
In this component too the helper has the wrong color

<img width="1114" alt="Screenshot 2024-09-17 at 14 12 05" src="https://github.com/user-attachments/assets/4b72191e-317d-40d6-af81-69116ed9f70a">

2024-09-17 16:09 UTC, matthprost approved these changes

2024-09-18 09:45 UTC, PetmePant approved these changes

2024-10-02 07:54 UTC, merged