feat(Row): change padding on Row and List.Row
scaleway/ultraviolet pull request #4262
Opened 2024-09-19 09:52 UTC by lisalupi

## Summary

## Type

- Feature

### Summarise concisely:

#### What is expected?
- `<Row />`  New prop `padding` to set a custom padding
- `<List.Row />` : New prop `paddingExpandable` to set a custom padding inside the expandable content

2024-09-19 14:20 UTC, matthprost requested changes

2024-09-19 14:20 UTC, matthprost commented on packages/ui/src/components/List/Row.tsx
> +      paddingExpandable,
```suggestion
      expandablePadding,
```

2024-10-07 09:22 UTC, matthprost approved these changes

2024-10-07 15:31 UTC, alexandre-combemorel approved these changes

2024-10-08 08:42 UTC, merged