fix(SelectInputV2): auto scroll
scaleway/ultraviolet pull request #4282
Opened 2024-09-26 09:20 UTC by lisalupi

## Summary

## Type

- Bug

### Summarise concisely:

#### What is expected?

When the dropdown is at the bottom of the screen, there is be an autoscroll to see it completely. 
Works inside a modal too.

2024-10-02 07:57 UTC, matthprost requested changes

2024-10-02 07:57 UTC, matthprost commented on packages/ui/src/components/SelectInputV2/Dropdown.tsx
> +  const [marginBottom, setMarginBottom] = useState(false)
Why don't we just always set the margin bottom? If the dropdown didn't reach the bottom of screen it will be an invisible margin no?

2024-10-04 07:23 UTC, matthprost approved these changes

2024-10-08 07:51 UTC, alexandre-combemorel approved these changes

2024-10-08 07:56 UTC, radhi-nasser-scaleway approved these changes

2024-10-08 08:48 UTC, merged