feat: shit click for multiselect
scaleway/ultraviolet pull request #4467
Opened 2024-11-18 09:54 UTC by lisalupi

## Summary

## Type

- Enhancement

### Summarise concisely:

#### What is expected?

`<List />` and `<Table />` : hold shift to multiselect when they are selectable

2024-11-19 14:43 UTC, matthprost requested changes

2024-11-19 14:43 UTC, matthprost commented on packages/ui/src/components/List/ListContext.tsx
> +    )
This won't work if you have multiple list / table in the same page. You need to find a more specific way to target it. Maybe the ref is the solution


https://github.com/user-attachments/assets/345d781c-6b91-4548-913f-07f4314ce37e

2024-11-21 10:36 UTC, DorianMaliszewski commented
Is it possible to add some unitary tests on it ?

2024-11-21 10:46 UTC, DorianMaliszewski approved these changes

2024-11-21 16:33 UTC, matthprost approved these changes

2024-11-25 14:28 UTC, DorianMaliszewski approved these changes

2024-11-26 10:01 UTC, matthprost approved these changes

2024-11-26 14:44 UTC, merged