refactor: pagination
scaleway/ultraviolet pull request #4537
Opened 2024-12-04 15:03 UTC by lisalupi

## Summary

## Type

- Refactor

### Summarise concisely:

#### What is expected?

Refactor and enhancement of `<Pagination />` : 
- Number of results on the bottom left 
- Number of items to display
- Styling

#### The following changes where made:

## Relevant logs and/or screenshots

| Page |   Before   |      After |
| :--- | :--------: | ---------: |
| url  | <img width="553" alt="Capture d’écran 2024-12-04 à 16 00 36" src="https://github.com/user-attachments/assets/c686a38f-cd04-4afc-ab9c-1432c660fc6b">|  <img width="517" alt="Capture d’écran 2024-12-04 à 16 00 02" src="https://github.com/user-attachments/assets/7f5873f2-9d46-45dd-b181-c70452d13b6b"> |
| url  | <img width="537" alt="Capture d’écran 2024-12-04 à 16 02 06" src="https://github.com/user-attachments/assets/c2816a6a-3eef-4ffb-935c-1f53d08ae8ec"> |  <img width="516" alt="Capture d’écran 2024-12-04 à 16 01 17" src="https://github.com/user-attachments/assets/53a8a03d-e152-431b-a37d-45589b5c88e1"> |

PerPage : 
<img width="1042" alt="Capture d’écran 2024-12-04 à 16 02 54" src="https://github.com/user-attachments/assets/598656f8-087b-446c-b8bc-0c4ecf932b9d">

2024-12-05 13:51 UTC, matthprost requested changes
You have some issues with your coverage, it seems that you are calling `onChange` in the test without using `vi.fn()`. I think this is what makes the codecov broken

2024-12-05 14:14 UTC, matthprost requested changes

2024-12-05 14:14 UTC, matthprost commented on packages/ui/src/components/Pagination/PaginationButtons.tsx
> +const Ellipsis = styled(PageButton)`
Why making it a button?

2024-12-05 14:14 UTC, matthprost commented on packages/ui/src/components/Pagination/PaginationButtons.tsx
> +                tabIndex={-1}
This won't be necessary if we don't make this as a button

2024-12-05 14:14 UTC, matthprost commented on packages/ui/src/components/Pagination/__stories__/PerPage.stories.tsx
> +  height: 210px;
no px please, rem only

2024-12-05 14:14 UTC, matthprost commented on packages/ui/src/components/Pagination/PaginationButtons.tsx
> +            <React.Fragment key={pageNumber}>
This is no good, we have an empty div here that shouldn't be there

<img width="844" alt="Screenshot 2024-12-05 at 15 09 37" src="https://github.com/user-attachments/assets/6a834cda-b5ae-4849-b9ba-acb72057c716">

2024-12-05 14:14 UTC, matthprost commented on packages/ui/src/components/Pagination/PaginationButtons.tsx
> +                aria-label={`Page ${pageNumber}`}
not needed I think, the children of the button should be explicit enough

2024-12-05 14:14 UTC, matthprost commented on packages/ui/src/components/Pagination/PerPage.tsx
> +]
```suggestion
const optionsItemsPerPage = [
  {
    value: '10',
    label: '10',
  },
  {
    value: '25',
    label: '25',
  },
  {
    value: '50',
    label: '50',
  },
  {
    value: '100',
    label: '100',
  },
] as const
```

2024-12-06 09:05 UTC, mhervouet commented
For pagination with item number per page, the size should be small for `selectInput` and `Buttons`

2024-12-09 09:41 UTC, DorianMaliszewski approved these changes

2024-12-10 08:56 UTC, johnrazeur approved these changes

2024-12-10 08:56 UTC, johnrazeur commented on packages/ui/src/components/Pagination/getPageNumbers.ts
> +      ? Array.from({ length: 3 }, (_, index) => currentPage + index - 1)
The `3` should be in a const.

2024-12-11 08:39 UTC, vincentaudebert commented on packages/ui/src/components/Pagination/PaginationButtons.tsx
> +const PageNumbersContainer = styled.div`
Could we not use Row and Stack around these? Maybe styled but at least it would reduce CSS

2025-01-15 09:44 UTC, merged